//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisGastosRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MisGastosEntities : DbContext
    {
        public MisGastosEntities()
            : base("name=MisGastosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConceptosIngreso> ConceptosIngresoes { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<ConceptosEgreso> ConceptosEgresoes { get; set; }
        public virtual DbSet<Egreso> Egresos { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Ingreso> Ingresos { get; set; }
    }
}
