//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisGastosRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egreso
    {
        public int IdEgreso { get; set; }
        public int IdUsuario { get; set; }
        public int IdConceptoEgreso { get; set; }
        public int IdMoneda { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaEgreso { get; set; }
    
        public virtual ConceptosEgreso ConceptosEgreso { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
