//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisGastosRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingreso
    {
        public int IdIngreso { get; set; }
        public int IdUsuario { get; set; }
        public int IdConceptoIngreso { get; set; }
        public int IdMoneda { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual ConceptosIngreso ConceptosIngreso { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
